accounts:
  - name: alice
    coins: ["1000carbon", "5000000stake"]
  - name: SETS
    coins: ["10000000stake"]
  - name: vietnam
    coins: ["45000000stake"]
  - name: investors
    coins: ["40000000stake"]

validator:
  name: SETS
  staked: "10000000stake"
  
client:
  vuex:
    path: "vue/src/store"

genesis: 
  chain_id: "SETS"
